on: pull_request
name: on pull request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: docker://mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.8
      with:
        args: dotnet build
